// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MassTransit.KafkaIntegration.Tests.AvroContracts.AvroContracts
{
    /// <summary>
	/// A simple Kafka message
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class KafkaMessage : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"KafkaMessage\",\"doc\":\"A simple Kafka message\",\"namespace\"" +
				":\"MassTransit.KafkaIntegration.Tests.AvroContracts\",\"fields\":[{\"name\":\"Test\",\"ty" +
				"pe\":\"string\"}]}");
		private string _Test;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return KafkaMessage._SCHEMA;
			}
		}
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				this._Test = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Test;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Test = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
