//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassTransit.DapperIntegration.Tests.IntegrationTests {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Sql {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MassTransit.DapperIntegration.Tests.IntegrationTests.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Jobs] (
        ///    [CorrelationId] UNIQUEIDENTIFIER NOT NULL,
        ///    [CurrentState] INT NOT NULL,    
        ///    [Completed] DATETIME NULL,
        ///    [Faulted] DATETIME NULL,
        ///    [Started] DATETIME NULL,
        ///    [Submitted] DATETIME NULL,    
        ///    [EndDate] DATETIMEOFFSET NULL,
        ///    [NextStartDate] DATETIMEOFFSET NULL,
        ///    [StartDate] DATETIMEOFFSET NULL,    
        ///    [AttemptId] UNIQUEIDENTIFIER NOT NULL,
        ///    [JobTypeId] UNIQUEIDENTIFIER NOT NULL,
        ///    [JobRetryDelayToken] UNIQUEIDENTIFIER NULL,
        ///    [JobSlot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateJobTables {
            get {
                return ResourceManager.GetString("CreateJobTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [dbo].[Jobs];
        ///DROP TABLE IF EXISTS [dbo].[JobAttempts];
        ///DROP TABLE IF EXISTS [dbo].[JobTypes];.
        /// </summary>
        internal static string DropJobTables {
            get {
                return ResourceManager.GetString("DropJobTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNCATE TABLE [dbo].[Jobs];
        ///TRUNCATE TABLE [dbo].[JobAttempts];
        ///TRUNCATE TABLE [dbo].[JobTypes];.
        /// </summary>
        internal static string ResetJobTables {
            get {
                return ResourceManager.GetString("ResetJobTables", resourceCulture);
            }
        }
    }
}
