// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnitTests
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// A simple Kafka message
	/// </summary>
	public partial class KafkaMessage : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"KafkaMessage\",\"namespace\":\"UnitTests\",\"fields\":[{\"name\":" +
				"\"Test\",\"type\":\"string\"}]}");
		private string _Test;
		public virtual Schema Schema
		{
			get
			{
				return KafkaMessage._SCHEMA;
			}
		}
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				this._Test = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Test;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Test = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
