// <auto-generated />
using System;
using MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MassTransit.EntityFrameworkCoreIntegration.Tests.Migrations.SagaWithDependency
{
    [DbContext(typeof(SagaWithDependencyContext))]
    partial class SagaWithDependencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess.SagaDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SagaInnerDependencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SagaInnerDependencyId");

                    b.ToTable("SagaDependency");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess.SagaInnerDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SagaInnerDependency");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.SagaWithDependency", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<Guid>("DependencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Initiated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("CorrelationId");

                    b.HasIndex("DependencyId");

                    b.ToTable("EfCoreSagasWithDepencies");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess.SagaDependency", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess.SagaInnerDependency", "SagaInnerDependency")
                        .WithMany()
                        .HasForeignKey("SagaInnerDependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.SagaWithDependency", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.Tests.SagaWithDependency.DataAccess.SagaDependency", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
