// Copyright 2007-2011 Chris Patterson, Dru Sellers, Travis Smith, et. al.
//  
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use 
// this file except in compliance with the License. You may obtain a copy of the 
// License at 
// 
//     http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software distributed 
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
// CONDITIONS OF ANY KIND, either express or implied. See the License for the 
// specific language governing permissions and limitations under the License.
namespace MassTransit.Transports.Msmq.Management
{
	using System;
	using System.IO;
	using Logging;
	using System.Diagnostics;

	public class Windows7Installer :
		MsmqInstaller
	{
		static readonly ILog _log = Logger.Get(typeof(Windows7Installer));

		public Process Install()
		{
			_log.DebugFormat("Installing MSMQ on Windows 7");

			string scriptFileName = Path.Combine(Path.GetTempPath(), "masstransit_msmq_installation.cmd");

			bool shouldForce64BitSystemFolder = IntPtr.Size == 4
												&& Environment.OSVersion.IsWin64BitOS();

			string dismPath = shouldForce64BitSystemFolder
				? Path.Combine(Environment.GetEnvironmentVariable("WINDIR") ?? @"C:\Windows", "Sysnative")
				: Environment.GetFolderPath(Environment.SpecialFolder.System);

			string contents =
				string.Format(
                    @"rem This script has been generated by MassTransit in order to install MSMQ and can be safely deleted.
{0} /Online /Enable-Feature /FeatureName:MSMQ-Container
{0} /Online /Enable-Feature /FeatureName:MSMQ-Server
{0} /Online /Enable-Feature /FeatureName:MSMQ-Multicast
",
					Path.Combine(dismPath, "dism.exe"));

			File.WriteAllText(scriptFileName, contents);

			_log.DebugFormat("Executing installation script: {0}", scriptFileName);

			return Process.Start(scriptFileName);
		}
	}
}