// <auto-generated />
using System;
using MassTransit.EntityFrameworkCoreIntegration.Turnout;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MassTransit.EntityFrameworkCoreIntegration.Tests.Migrations.TurnoutSagaDb
{
    [DbContext(typeof(TurnoutSagaDbContext))]
    partial class TurnoutSagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MassTransit.Turnout.Components.StateMachines.TurnoutJobAttemptState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstanceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StatusCheckTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CorrelationId");

                    b.HasIndex("JobId", "RetryAttempt")
                        .IsUnique();

                    b.ToTable("TurnoutJobAttemptState");
                });

            modelBuilder.Entity("MassTransit.Turnout.Components.StateMachines.TurnoutJobState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JobSlotRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobSlotWaitToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("JobTimeout")
                        .HasColumnType("time");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StartJobRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Submitted")
                        .HasColumnType("datetime2");

                    b.HasKey("CorrelationId");

                    b.HasIndex("JobSlotRequestId")
                        .IsUnique();

                    b.HasIndex("StartJobRequestId")
                        .IsUnique();

                    b.ToTable("TurnoutJobState");
                });

            modelBuilder.Entity("MassTransit.Turnout.Components.StateMachines.TurnoutJobTypeState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveJobCount")
                        .HasColumnType("int");

                    b.Property<string>("ActiveJobs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConcurrentJobLimit")
                        .HasColumnType("int");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int?>("OverrideJobLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OverrideLimitExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("CorrelationId");

                    b.ToTable("TurnoutJobTypeState");
                });
#pragma warning restore 612, 618
        }
    }
}
