// Copyright 2007-2008 The Apache Software Foundation.
//  
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use 
// this file except in compliance with the License. You may obtain a copy of the 
// License at 
// 
//     http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software distributed 
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
// CONDITIONS OF ANY KIND, either express or implied. See the License for the 
// specific language governing permissions and limitations under the License.
using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly : ComVisible(false)]
[assembly : CLSCompliant(true)]
[assembly : AssemblyCompany("CFT & ACM")]
[assembly : AssemblyVersion("0.8.0.2091")]
[assembly : AssemblyFileVersion("0.8.0.2091")]
[assembly : AssemblyInformationalVersion("0.8.0.2091")]
[assembly : AssemblyTitle("MassTransit")]
[assembly : AssemblyProduct("MassTransit")]
[assembly : AssemblyDescription("MassTransit is a product of CFT & ACM")]
[assembly : AssemblyTrademark("MassTransit - CFT & ACM")]
[assembly : AssemblyCopyright("Copyright 2009 CFT & ACM, - Original author or authors")]